name: Run swedish

on:
  schedule:
    - cron: '0 22,0,2,4,6,8,10,12 * * *'  # 日本時間 7〜21時、2時間おき
  workflow_dispatch:  # 手動でも実行可能

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install packages
        run: |
          pip install -r requirements.txt
          playwright install chromium

      - name: Run script
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: python swedish.py
